# Question 1

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [5]:
import numpy as np

arr = [x for x in range(2,51,3)]
print(arr)
np_arr = np.array(arr)
print(np_arr)
print(type(arr))
print(type(np_arr))

[2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50]
[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]
<class 'list'>
<class 'numpy.ndarray'>


# Question 2

Accept two lists of 5 elements each from the user.

Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [11]:
import numpy as np
n = 6
list_a = []
list_b = []
for i in range(5):
    x = int(input())
    y = int(input()) 
    list_a.append(x)
    list_b.append(y)
print("List 1 = ",list_a,"\nList 2 = ",list_b)
np_arr1 = np.array(list_a)
np_arr2 = np.array(list_b)   
np.concatenate((np_arr1,np_arr2), axis=None)


0
1
2
3
4
5
6
7
8
9
List 1 =  [0, 2, 4, 6, 8] 
List 2 =  [1, 3, 5, 7, 9]


array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

# Question 3

Write a code snippet to find the dimensions of an ndarray and its size.

In [20]:
import numpy as np

arr = np.arange(36).reshape(2,9,2)
print(arr)
print()
print("Dimension of the numpy array is: ", str(arr.ndim))
print()
print("Shape of the numpy array is: ", str(arr.shape))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]
  [30 31]
  [32 33]
  [34 35]]]

Dimension of the numpy array is:  3

Shape of the numpy array is:  (2, 9, 2)


# Question 4

How to convert a 1D array into a 2D array? Demonstrate with the help of a code.

Hint: np.newaxis, np.expand_dims

In [31]:
import numpy as np

#consider a 1D array
arr1D = np.arange(8)
print(arr1D)
print("Shape of above array is: ",arr1D.shape)
print()
# np.newaxis increases the dimension of an array by 1. Here, 1D array will be converted to a 2D array
arr2D = arr1D[:,np.newaxis]
# this is equivalent to np.expand_dims(arr1D,axis=1)
# Here, the dimension changes from 1 to 2. The shape of the array becomes (8,1)
print(arr2D)
print("Shape of above array is: ", arr2D.shape)

[0 1 2 3 4 5 6 7]
Shape of above array is:  (8,)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
Shape of above array is:  (8, 1)


# Question 5

Consider two square numpy. Stack them vertically and horizontally.

Hint: Use vstack(), hstack()

In [55]:
import numpy as np
np1 = np.matrix([[1,2],[2,1]])
print("Matrix 1  \n", np1)
print()
np2 = np.arange(4).reshape(2,2)
print("Matrix 2  \n", np2)
print()
print("Vertical Stack  \n", np.vstack((np1,np2)))
print()
print("Horizontal Stack  \n", np.hstack((np1,np2)))

Matrix 1  
 [[1 2]
 [2 1]]

Matrix 2  
 [[0 1]
 [2 3]]

Vertical Stack  
 [[1 2]
 [2 1]
 [0 1]
 [2 3]]

Horizontal Stack  
 [[1 2 0 1]
 [2 1 2 3]]


# Question 6

How to get unique items and counts of unique items?

In [66]:
import numpy as np

a = np.array([1,2,3,1,5,2,4,5,6,4,3,6,7,6,8,8,2,6,8,9])
print(a)
u = np.unique(a) #returns unique elements from the given numpy array
print(u)
p,counts = np.unique(a,return_counts=True) #returns the count of each unique element
p
print(counts)
print("The unique elements",p,"occur with the count",counts, "respectively")

[1 2 3 1 5 2 4 5 6 4 3 6 7 6 8 8 2 6 8 9]
[1 2 3 4 5 6 7 8 9]
[2 3 2 2 2 4 1 3 1]
The unique elements [1 2 3 4 5 6 7 8 9] occur with the count [2 3 2 2 2 4 1 3 1] respectively
